SPREAD_GROUP_NAME = "jhuVDL"
SPREAD_DAEMON_PORT = '4803'
SPREAD_MAX_MESSAGE_SIZE = 140000
SPREAD_MBOX_POLL_INTERVAL = 0.0005

MCAST_ADDR = '224.44.44.44'
START_MCAST_PORT_NUM = 12345
PEER_PORT_NUM = 12468
SOCK_TIMEOUT_VAL = 0.05
CHUNK_SEND_INTERVAL = 0.002
RECV_CHUNKS_TIMEOUT_VAL = 0.05

START_SPREAD_SIGNAL = START_MCAST_SIGNAL = "START_MCAST"
INIT_WEIGHTS_TAG = "INIT_W"

MAX_PACKET_SIZE = 1460              # maximum UDP packet size to send over the network

PACKET_SIZE_TAG = "Arnold"
LEN_PACKET_SIZE_TAG = 6

VERBOSE_LVL = 2
