SPREAD_GROUP_NAME = "jhuVDL"
SPREAD_DAEMON_PORT = '4803'
SPREAD_MBOX_POLL_INTERVAL = 0.0005

MCAST_ADDR = '224.44.44.44'
START_MCAST_PORT_NUM = 12345
PEER_PORT_NUM = 12468
SOCK_TIMEOUT_VAL = 0.05
CHUCK_SEND_INTERVAL = 0.002

START_SPREAD_SIGNAL = START_MCAST_SIGNAL = "START_MCAST"
INIT_WEIGHTS_TAG = "INIT_W"

MAX_PACKET_SIZE = 1460              # maximum UDP packet size to send over the network

MAX_BITS_IMAGE_SIZE = 24            # maximum number of bits used to represent the size of an image
IMAGE_SIZE_PACKET_TAG = "Arnold"
LEN_IMAGE_SIZE_PACKET_TAG = 6

VERBOSE_LVL = 1
