Ssrc C++/Lua/Perl/Python/Ruby Bindings for Spread API 1.0.13: Mailbox.cc File Reference
Mailbox.cc File Reference
#include <ssrc/spread/Mailbox.h>
#include <fcntl.h>
Functions
groups resize (groups.capacity())
message init_pre_receive ()
if (!_drop_receive)
else if (result< 0 &&result !=Error::GroupsTooShort &&result !=Error::BufferTooShort) throw Error(result)
message set_type (type)
message set_service (stype)
message set_sender (sender)
message set_endian_mismatch (endian_mismatch !=0)
groups resize (num_groups)
message init_post_receive (result)
Variables
int Error
BaseMessage::message_type type
BaseMessage::service_type stype = (_drop_receive ? BaseMessage::DropReceive : 0)
Spread::group_type sender
try_again __pad0__
try_again num_groups = 0
try_again endian_mismatch = 0
result
Function Documentation
if() [1/2]
if (! _drop_receive)
Definition at line 188 of file Mailbox.cc.
References __END_NS_SSRC_SPREAD, Error::BufferTooShort, ScatterMessage::count_message_objects(), Error, Error::GroupsTooShort, result, BaseMessage::set_endian_mismatch(), BaseMessage::set_sender(), BaseMessage::set_service(), BaseMessage::set_type(), Message::size(), and ScatterMessage::size().
if() [2/2]
else if ()
init_post_receive()
message init_post_receive (result)
init_pre_receive()
message init_pre_receive ()
resize() [1/2]
groups resize (groups. capacity())
Referenced by GroupList::add(), and GroupList::operator=().
resize() [2/2]
groups resize (num_groups)
set_endian_mismatch()
message set_endian_mismatch (endian_mismatch ! = 0)
set_sender()
message set_sender (sender)
set_service()
message set_service (stype)
set_type()
message set_type (type)
Variable Documentation
__pad0__
try_again __pad0__
Definition at line 181 of file Mailbox.cc.
endian_mismatch
try_again endian_mismatch = 0
Definition at line 181 of file Mailbox.cc.
Error
int Error
Initial value:
{
int result, num_groups, endian_mismatch
Definition at line 171 of file Mailbox.cc.
Referenced by if(), Mailbox::join(), Mailbox::leave(), Mailbox::Mailbox(), Mailbox::poll(), and Mailbox::send().
num_groups
try_again num_groups = 0
Definition at line 181 of file Mailbox.cc.
result
return result
Initial value:
=
Spread::SP_scat_receive(_mbox, &stype, sender, groups.size(), &num_groups,
groups.groups(), &type, &endian_mismatch,
message.scatter())
Definition at line 184 of file Mailbox.cc.
Referenced by if(), Mailbox::join(), Mailbox::leave(), Mailbox::Mailbox(), Mailbox::poll(), and Mailbox::send().
sender
Spread::group_type sender
Definition at line 175 of file Mailbox.cc.
stype
stype = (_drop_receive ? BaseMessage::DropReceive : 0)
Definition at line 174 of file Mailbox.cc.
type
BaseMessage::message_type type
Definition at line 173 of file Mailbox.cc.
Referenced by Mailbox::send().
Copyright © 2006-2015 Savarese Software Research Corporation. All rights reserved.